name: Deploy Functions
on:
  push:
    branches: [main]
jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD }}
          export_default_credentials: true
      - name: Cloud Functions Deploy
        run: gcloud functions deploy hello_gcs --runtime=python37 --entry_point=hello_gcs --trigger-resource account-linking-testing.appspot.com --trigger-event google.storage.object.finalize
        id: Deploy
      - name: test
        run: curl "${{ steps.deploy.outputs.url }}"
