name: Deploy Functions
on:
  push:
    branches: [main]
jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD }}
        export_default_credentials: true
    - name: Cloud Functions Deploy
      id: Deploy
      uses: google-github-actions/deploy-cloud-functions@v0.1.2
      with:
        name: hello_gcs
        runtime: python37
        entry_point: hello_gcs
        source_dir: functions/
        event_trigger_type: providers/cloud.storage/eventTypes/object.finalize
        event_trigger_resource: projects/_/buckets/account-linking-testing.appspot.com
    - name: test
      run: curl "${{ steps.deploy.outputs.url }}"
