name: Deploy Functions
on:
  push:
    branches: [main]
jobs:
  deploy_functions:
    name: deploy functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      CI_CD: True
      GCLOUD: ${{ secrets.GCLOUD }}
    runs-on: ubuntu-latest
    container: crazzywizard/voice_essentials_image:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: npm install
        run: npm ci
        working-directory: ./functions
      - name: Install Python Modules
        run: python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: ./functions
      - name: Deploy to firebase
        run: python deploy.py --all
        working-directory: ./functions
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
