name: Deploy Functions
on:
  push:
    branches: [main]
jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        export_default_credentials: true
    - name: Cloud Functions Deploy
      id: Deploy
      uses: google-github-actions/deploy-cloud-functions@v0.1.2
      workingdir: ./functions
      with:
        name: hello_name
        runtime: python37
        entry_point: hello_name
    - name: test
      run: curl "${{ steps.deploy.outputs.url }}"
